# Generated by Django 5.2.6 on 2025-09-17 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                                           primary_key=True,
                                           serialize=False,
                                           verbose_name='ID'
                                           )),
                ('name', models.CharField(max_length=120)),
                ('country', models.CharField(blank=True,
                                             default='',
                                             max_length=120
                                             )),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('name', 'country'),
                                name='uq_city_country')],
            },
        ),
    ]
