# Generated by Django 5.2.6 on 2025-09-17 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meteo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HourlyWeather',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                                           primary_key=True,
                                           serialize=False,
                                           verbose_name='ID'
                                           )),
                ('date_time', models.DateTimeField(db_index=True)),
                ('temperature_2m', models.FloatField(null=True)),
                ('precipitation', models.FloatField(null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                           related_name='hourly',
                                           to='meteo.city'
                                           )),
            ],
            options={
                'indexes': [models.Index(fields=['city', 'date_time'],
                                         name='meteo_hourl_city_id_82c812_idx')],
                'constraints': [models.UniqueConstraint(fields=('city', 'date_time'),
                                                        name='uq_city_datetime')],
            },
        ),
    ]
